/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProjectsSchema {
  $schema?: string;
  projects: Project[];
}
export interface Project {
  /**
   * The title of the project
   */
  title: string;
  /**
   * The description of the project
   */
  description: string;
  /**
   * The repository from which to pull the static assets
   */
  repository: string;
  /**
   * The branch to pull the static assets from
   */
  branch?: string;
  /**
   * The public/... subdirectory where to save the static assets pulled from the repository
   */
  subdirectory: string;
  /**
   * The most appropriate category for the project
   */
  category: "library" | "tool";
}
