name: Pull Project Documentation

on:
  repository_dispatch:
    types: [submit-project-docs]
  workflow_dispatch:
    inputs:
      project_repository:
        description: "The project repository to pull docs from. An item with the corresponding `repository` must be defined in projects.json"
        required: true

jobs:
  pull-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: generate_token
        with:
          app-id: ${{ vars.PR_AUTOMATION_BOT_PUBLIC_APP_ID }}
          private-key: ${{ secrets.PR_AUTOMATION_BOT_PUBLIC_PRIVATE_KEY }}

      - name: Checkout this repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Deno
        uses: dfinity/ci-tools/actions/setup-deno@main

      - name: Prepare parameters
        id: params
        run: |
          echo "project_repository=${{ github.event.client_payload.project_repository || inputs.project_repository }}" >> $GITHUB_OUTPUT

      - name: Pull project documentation
        run: |
          deno task pull-project-docs --project "${{ steps.params.outputs.project_repository }}"

      - name: Create pull request
        uses: dfinity/ci-tools/actions/create-pr@main
        with:
          branch_name: "build/docs-update"
          base_branch_name: "main"
          pull_request_title: "build: update project docs"
          pull_request_body: "This pull request was automatically created to update the project documentation from ${{ steps.params.outputs.project_repository }}."
          commit_message: "build: update docs for ${{ steps.params.outputs.project_repository }}"
          token: ${{ steps.generate_token.outputs.token }}
