name: Pull Project Docs

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Project to pull docs for"
        required: true
        type: string

concurrency:
  group: pr-${{ github.workflow }}-${{ inputs.project }}
  cancel-in-progress: true

jobs:
  pull-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Pull project docs
        run: |
          deno task pull-project-docs --project=${{ inputs.project }}
