name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://js.icp.build
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno i

      - name: Deploy Docs to Juno satellite
        uses: junobuild/juno-action@12d3046b808750b1bdc778451900d021e9bc68d5 # v0.4.8
        with:
          args: deploy --mode production --immediate
        env:
          JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}
