name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://js.icp.build
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Deno
        uses: dfinity/ci-tools/actions/setup-deno@main

      - name: Install dependencies
        run: deno i

      - name: Deploy Docs to Juno satellite
        env:
          # The identity corresponding to this token must be an Administrator of the satellite
          # in order to have permissions to apply the config (what the --config flag does)
          JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}
        run: deno task juno deploy --config --mode production --immediate
